/**
 * Alternate spellings / formal names → first label is canonical English key for matching.
 * Used with foldGeoLabel() so filters and ranking rows align.
 */
export const COUNTRY_ALIAS_GROUPS: string[][] = [
  [
    "china",
    "people's republic of china",
    "pr china",
    "prc",
    "china, people's republic of",
    "china (mainland)",
    "mainland china",
  ],
  ["hong kong", "hong kong sar", "hong kong, china", "hksar"],
  ["macao", "macau", "macau sar", "macao sar, china"],

  ["south korea", "republic of korea", "korea, republic of", "korea (south)", "rok", "south-korea"],
  ["north korea", "korea (north)", "democratic people's republic of korea", "dprk"],

  ["united states", "usa", "u.s.", "u.s.a.", "united states of america", "u.s.a", "america"],
  ["canada"],

  ["united kingdom", "uk", "great britain", "britain", "england", "scotland", "wales", "northern ireland"],
  ["ireland", "republic of ireland", "éire", "eire"],

  ["germany", "deutschland", "federal republic of germany"],
  ["france", "french republic", "république française", "republique francaise"],
  ["italy", "italia", "italian republic"],
  ["spain", "españa", "espana", "kingdom of spain"],
  ["netherlands", "holland", "the netherlands", "kingdom of the netherlands"],
  ["belgium", "kingdom of belgium"],
  ["switzerland", "swiss confederation"],
  ["austria", "republic of austria"],
  ["sweden", "kingdom of sweden"],
  ["norway", "kingdom of norway"],
  ["denmark", "kingdom of denmark"],
  ["finland", "republic of finland"],
  ["poland", "republic of poland"],
  ["portugal", "portuguese republic"],
  ["greece", "hellenic republic"],
  ["czechia", "czech republic"],
  ["hungary"],
  ["romania"],
  ["bulgaria", "republic of bulgaria"],
  ["croatia", "republic of croatia"],
  ["slovakia", "slovak republic"],
  ["slovenia", "republic of slovenia"],
  ["serbia", "republic of serbia"],
  ["bosnia and herzegovina", "bosnia", "bih"],
  ["north macedonia", "macedonia", "republic of north macedonia"],
  ["albania", "republic of albania"],
  ["ukraine"],
  ["belarus", "republic of belarus"],
  ["lithuania", "republic of lithuania"],
  ["latvia", "republic of latvia"],
  ["estonia", "republic of estonia"],
  ["russia", "russian federation"],
  ["moldova", "republic of moldova"],
  ["georgia"],
  ["armenia", "republic of armenia"],
  ["azerbaijan", "republic of azerbaijan"],

  ["türkiye", "turkey", "republic of turkey", "turkiye"],
  ["israel", "state of israel"],
  ["saudi arabia", "kingdom of saudi arabia", "ksa"],
  ["united arab emirates", "uae", "the uae", "dubai", "abu dhabi"],
  ["qatar", "state of qatar"],
  ["kuwait", "state of kuwait"],
  ["bahrain", "kingdom of bahrain"],
  ["oman", "sultanate of oman"],
  ["jordan", "hashemite kingdom of jordan"],
  ["lebanon", "lebanese republic"],
  ["iraq", "republic of iraq"],
  ["iran", "islamic republic of iran", "persia"],
  ["syria", "syrian arab republic"],
  ["yemen", "republic of yemen"],
  ["palestine", "state of palestine", "palestinian territory"],
  ["egypt", "arab republic of egypt"],
  ["morocco", "kingdom of morocco"],
  ["algeria", "people's democratic republic of algeria"],
  ["tunisia", "tunisian republic"],
  ["south africa", "republic of south africa"],
  ["nigeria", "federal republic of nigeria"],
  ["kenya", "republic of kenya"],
  ["ethiopia", "federal democratic republic of ethiopia"],
  ["ghana", "republic of ghana"],
  ["uganda", "republic of uganda"],
  ["tanzania", "united republic of tanzania"],
  ["zimbabwe", "republic of zimbabwe"],
  ["cameroon", "republic of cameroon"],
  ["ivory coast", "côte d'ivoire", "cote d'ivoire", "cote divoire"],
  ["senegal", "republic of senegal"],
  ["sudan", "republic of the sudan"],
  ["angola", "republic of angola"],
  ["mozambique", "republic of mozambique"],
  ["democratic republic of the congo", "congo (kinshasa)", "drc"],
  ["congo", "republic of the congo", "congo (brazzaville)"],

  ["japan", "nihon", "nippon"],
  ["india", "republic of india", "bharat"],
  ["pakistan", "islamic republic of pakistan"],
  ["bangladesh", "people's republic of bangladesh"],
  ["indonesia", "republic of indonesia"],
  ["malaysia"],
  ["thailand", "kingdom of thailand", "siam"],
  ["vietnam", "viet nam", "socialist republic of vietnam"],
  ["philippines", "republic of the philippines"],
  ["singapore", "republic of singapore"],
  ["myanmar", "burma"],
  ["cambodia", "kingdom of cambodia"],
  ["laos", "lao people's democratic republic", "lao pdr"],
  ["sri lanka", "democratic socialist republic of sri lanka"],
  ["nepal", "federal democratic republic of nepal"],
  ["afghanistan", "islamic republic of afghanistan"],
  ["uzbekistan", "republic of uzbekistan"],
  ["kazakhstan", "republic of kazakhstan"],
  ["kyrgyzstan", "kyrgyz republic"],
  ["tajikistan", "republic of tajikistan"],
  ["turkmenistan"],
  ["mongolia"],
  ["brunei", "brunei darussalam"],
  ["maldives", "republic of maldives"],
  ["bhutan", "kingdom of bhutan"],

  ["australia", "commonwealth of australia"],
  ["new zealand", "aotearoa"],

  ["mexico", "méxico", "united mexican states"],
  [
    "brazil",
    "brasil",
    "federative republic of brazil",
    "republic of brazil",
    "brazil, federative republic of",
  ],
  ["argentina", "argentine republic"],
  ["chile", "republic of chile"],
  ["colombia", "plurinational state of colombia", "republic of colombia"],
  ["peru", "republic of peru"],
  ["venezuela", "venezuela (bolivarian republic of)", "bolivarian republic of venezuela"],
  ["ecuador", "republic of ecuador"],
  ["bolivia", "bolivia (plurinational state of)", "plurinational state of bolivia"],
  ["paraguay", "republic of paraguay"],
  ["uruguay", "oriental republic of uruguay"],
  ["cuba", "republic of cuba"],
  ["jamaica"],
  ["trinidad and tobago", "republic of trinidad and tobago"],
  ["costa rica", "republic of costa rica"],
  ["panama", "republic of panama"],
  ["guatemala", "republic of guatemala"],
  ["honduras", "republic of honduras"],
  ["el salvador", "republic of el salvador"],
  ["dominican republic"],
  ["haiti"],
  ["puerto rico"],

  ["taiwan", "taiwan, province of china", "chinese taipei", "republic of china"],
];
